### ISSUE TITLE
weight

### ISSUE THREAD

**Issue by Xliecc** [RazrabGit/SchoolDungeon#12]
Can I increase the weight of school dungeons in school generation, as schools can sometimes have other dungeons inside?

**Comment by RazrabGit** [comment]
Unfortunately, it doesn't work yet. There are some small problems with my editor. My project is based on an old version of the Unity template project by Evasia, because of this the mod has bugs. I can't fix it yet, I have studies, and I want to take a break from modding, and fixing it will take a lot, because I need to transfer the mod to the project, this caused me some problems. As soon as I rest, and studying will not burden me too much, I will fix the bug.

**Comment by Xliecc** [comment]
Thank，Rest well
